const input = (id, symbol, label, unit = "") => ({ id, symbol, label, unit });
const output = (symbol, label, unit = "") => ({ id: "result", symbol, label, unit });

export const ADVANCED_FORMULAS = [
  { id: "binomial-square", name: "Kwadrat sumy", category: "Algebra", equation: "(a+b)² = a²+2ab+b²", description: "Rozwinięcie kwadratu sumy dwóch wyrażeń.", inputs: [input("a", "a", "Składnik A"), input("b", "b", "Składnik B")], output: output("y", "Wartość"), expression: "a ^ 2 + 2 * a * b + b ^ 2", tags: ["tożsamość", "dwumian"] },
  { id: "difference-squares", name: "Różnica kwadratów", category: "Algebra", equation: "a²−b² = (a−b)(a+b)", description: "Tożsamość używana przy rozkładzie na czynniki.", inputs: [input("a", "a", "Wartość A"), input("b", "b", "Wartość B")], output: output("y", "Różnica kwadratów"), expression: "a ^ 2 - b ^ 2", tags: ["tożsamość"] },
  { id: "complex-modulus", name: "Moduł liczby zespolonej", category: "Algebra", equation: "|z| = √(a²+b²)", description: "Odległość liczby z=a+bi od początku układu.", inputs: [input("real", "a", "Część rzeczywista"), input("imaginary", "b", "Część urojona")], output: output("|z|", "Moduł"), expression: "sqrt(real ^ 2 + imaginary ^ 2)", tags: ["liczby zespolone"] },
  { id: "matrix-trace-2", name: "Ślad macierzy 2×2", category: "Algebra", equation: "tr(A) = a+d", description: "Suma elementów na głównej przekątnej macierzy.", inputs: [input("a", "a", "A₁₁"), input("d", "d", "A₂₂")], output: output("tr A", "Ślad"), expression: "a + d", tags: ["macierz"] },
  { id: "determinant-3x3", name: "Wyznacznik macierzy 3×3", category: "Algebra", equation: "det A = aei+bfg+cdh−ceg−bdi−afh", description: "Wyznacznik macierzy trzeciego stopnia metodą Sarrusa.", inputs: [input("a", "a", "A₁₁"), input("b", "b", "A₁₂"), input("c", "c", "A₁₃"), input("d", "d", "A₂₁"), input("e1", "e", "A₂₂"), input("f", "f", "A₂₃"), input("g", "g", "A₃₁"), input("h", "h", "A₃₂"), input("i", "i", "A₃₃")], output: output("det A", "Wyznacznik"), expression: "a * e1 * i + b * f * g + c * d * h - c * e1 * g - b * d * i - a * f * h", tags: ["macierz", "Sarrus"] },
  { id: "quadratic-factored", name: "Postać iloczynowa paraboli", category: "Algebra", equation: "y = a(x−x₁)(x−x₂)", description: "Wartość funkcji kwadratowej zapisana przez miejsca zerowe.", inputs: [input("a", "a", "Współczynnik"), input("x", "x", "Argument"), input("root1", "x₁", "Miejsce zerowe 1"), input("root2", "x₂", "Miejsce zerowe 2")], output: output("y", "Wartość"), expression: "a * (x - root1) * (x - root2)", tags: ["parabola"] },

  { id: "midpoint-x", name: "Środek odcinka — X", category: "Geometria analityczna", equation: "xₛ = (x₁+x₂)/2", description: "Współrzędna x środka odcinka.", inputs: [input("x1", "x₁", "X punktu 1"), input("x2", "x₂", "X punktu 2")], output: output("xₛ", "X środka"), expression: "(x1 + x2) / 2", tags: ["punkty"] },
  { id: "midpoint-y", name: "Środek odcinka — Y", category: "Geometria analityczna", equation: "yₛ = (y₁+y₂)/2", description: "Współrzędna y środka odcinka.", inputs: [input("y1", "y₁", "Y punktu 1"), input("y2", "y₂", "Y punktu 2")], output: output("yₛ", "Y środka"), expression: "(y1 + y2) / 2", tags: ["punkty"] },
  { id: "point-line-distance", name: "Odległość punktu od prostej", category: "Geometria analityczna", equation: "d = |Ax₀+By₀+C|/√(A²+B²)", description: "Najkrótsza odległość punktu od prostej Ax+By+C=0.", inputs: [input("A", "A", "Współczynnik A"), input("B", "B", "Współczynnik B"), input("C", "C", "Współczynnik C"), input("x0", "x₀", "X punktu"), input("y0", "y₀", "Y punktu")], output: output("d", "Odległość"), expression: "abs(A * x0 + B * y0 + C) / sqrt(A ^ 2 + B ^ 2)", tags: ["prosta", "punkt"] },
  { id: "coordinate-triangle-area", name: "Pole trójkąta ze współrzędnych", category: "Geometria analityczna", equation: "P = |x₁(y₂−y₃)+x₂(y₃−y₁)+x₃(y₁−y₂)|/2", description: "Pole trójkąta wyznaczonego przez trzy punkty.", inputs: [input("x1", "x₁", "X₁"), input("y1", "y₁", "Y₁"), input("x2", "x₂", "X₂"), input("y2", "y₂", "Y₂"), input("x3", "x₃", "X₃"), input("y3", "y₃", "Y₃")], output: output("P", "Pole"), expression: "abs(x1 * (y2 - y3) + x2 * (y3 - y1) + x3 * (y1 - y2)) / 2", tags: ["trójkąt", "punkty"] },
  { id: "line-point-slope", name: "Prosta z punktu i nachylenia", category: "Geometria analityczna", equation: "y = y₀+m(x−x₀)", description: "Wartość prostej przechodzącej przez zadany punkt.", inputs: [input("x0", "x₀", "X znanego punktu"), input("y0", "y₀", "Y znanego punktu"), input("slope", "m", "Nachylenie"), input("x", "x", "Argument")], output: output("y", "Wartość Y"), expression: "y0 + slope * (x - x0)", tags: ["prosta"] },
  { id: "polar-x", name: "Współrzędne biegunowe → X", category: "Geometria analityczna", equation: "x = r cosθ", description: "Współrzędna kartezjańska x z promienia i kąta.", inputs: [input("radius", "r", "Promień"), input("angle", "θ", "Kąt", "rad")], output: output("x", "Współrzędna X"), expression: "radius * cos(angle)", tags: ["biegunowe"] },
  { id: "polar-y", name: "Współrzędne biegunowe → Y", category: "Geometria analityczna", equation: "y = r sinθ", description: "Współrzędna kartezjańska y z promienia i kąta.", inputs: [input("radius", "r", "Promień"), input("angle", "θ", "Kąt", "rad")], output: output("y", "Współrzędna Y"), expression: "radius * sin(angle)", tags: ["biegunowe"] },

  { id: "prism-volume", name: "Objętość graniastosłupa", category: "Geometria 3D", equation: "V = Pₚh", description: "Objętość dowolnego graniastosłupa.", inputs: [input("baseArea", "Pₚ", "Pole podstawy"), input("height", "h", "Wysokość")], output: output("V", "Objętość"), expression: "baseArea * height", tags: ["graniastosłup"] },
  { id: "regular-tetrahedron-volume", name: "Objętość czworościanu foremnego", category: "Geometria 3D", equation: "V = a³/(6√2)", description: "Objętość foremnego czworościanu o krawędzi a.", inputs: [input("side", "a", "Krawędź")], output: output("V", "Objętość"), expression: "side ^ 3 / (6 * sqrt(2))", tags: ["czworościan"] },
  { id: "torus-volume", name: "Objętość torusa", category: "Geometria 3D", equation: "V = 2π²Rr²", description: "Objętość torusa z promienia głównego R i promienia przekroju r.", inputs: [input("majorRadius", "R", "Promień główny"), input("minorRadius", "r", "Promień przekroju")], output: output("V", "Objętość"), expression: "2 * pi ^ 2 * majorRadius * minorRadius ^ 2", tags: ["torus"] },
  { id: "torus-surface", name: "Pole powierzchni torusa", category: "Geometria 3D", equation: "S = 4π²Rr", description: "Pole powierzchni torusa.", inputs: [input("majorRadius", "R", "Promień główny"), input("minorRadius", "r", "Promień przekroju")], output: output("S", "Pole powierzchni"), expression: "4 * pi ^ 2 * majorRadius * minorRadius", tags: ["torus"] },
  { id: "cone-frustum-volume", name: "Objętość stożka ściętego", category: "Geometria 3D", equation: "V = πh(R²+Rr+r²)/3", description: "Objętość bryły między dwiema równoległymi podstawami stożka.", inputs: [input("largeRadius", "R", "Duży promień"), input("smallRadius", "r", "Mały promień"), input("height", "h", "Wysokość")], output: output("V", "Objętość"), expression: "pi * height * (largeRadius ^ 2 + largeRadius * smallRadius + smallRadius ^ 2) / 3", tags: ["stożek ścięty"] },

  { id: "derivative-sine", name: "Pochodna sinusa", category: "Analiza", equation: "(sin x)' = cos x", description: "Wartość pochodnej sinusa w punkcie x.", inputs: [input("x", "x", "Punkt", "rad")], output: output("f′(x)", "Pochodna"), expression: "cos(x)", tags: ["pochodna"] },
  { id: "derivative-cosine", name: "Pochodna cosinusa", category: "Analiza", equation: "(cos x)' = −sin x", description: "Wartość pochodnej cosinusa w punkcie x.", inputs: [input("x", "x", "Punkt", "rad")], output: output("f′(x)", "Pochodna"), expression: "-sin(x)", tags: ["pochodna"] },
  { id: "derivative-exponential", name: "Pochodna eˣ", category: "Analiza", equation: "(eˣ)' = eˣ", description: "Pochodna naturalnej funkcji wykładniczej.", inputs: [input("x", "x", "Punkt")], output: output("f′(x)", "Pochodna"), expression: "exp(x)", tags: ["pochodna"] },
  { id: "derivative-logarithm", name: "Pochodna logarytmu naturalnego", category: "Analiza", equation: "(ln x)' = 1/x", description: "Pochodna ln(x) dla dodatniego x.", inputs: [input("x", "x", "Punkt")], output: output("f′(x)", "Pochodna"), expression: "1 / x", tags: ["pochodna"], assumptions: ["x > 0"] },
  { id: "integral-sine", name: "Całka oznaczona sinusa", category: "Analiza", equation: "∫sin x dx [a,b] = cos a−cos b", description: "Pole algebraiczne sinusa na przedziale.", inputs: [input("xStart", "a", "Początek", "rad"), input("xEnd", "b", "Koniec", "rad")], output: output("I", "Całka"), expression: "cos(xStart) - cos(xEnd)", tags: ["całka"] },
  { id: "integral-cosine", name: "Całka oznaczona cosinusa", category: "Analiza", equation: "∫cos x dx [a,b] = sin b−sin a", description: "Pole algebraiczne cosinusa na przedziale.", inputs: [input("xStart", "a", "Początek", "rad"), input("xEnd", "b", "Koniec", "rad")], output: output("I", "Całka"), expression: "sin(xEnd) - sin(xStart)", tags: ["całka"] },
  { id: "integral-exponential", name: "Całka oznaczona eˣ", category: "Analiza", equation: "∫eˣdx [a,b] = eᵇ−eᵃ", description: "Całka funkcji wykładniczej na przedziale.", inputs: [input("xStart", "a", "Początek"), input("xEnd", "b", "Koniec")], output: output("I", "Całka"), expression: "exp(xEnd) - exp(xStart)", tags: ["całka"] },
  { id: "product-derivative", name: "Reguła iloczynu", category: "Analiza", equation: "(uv)' = u'v+uv'", description: "Pochodna iloczynu z wartości funkcji i ich pochodnych.", inputs: [input("du", "u′", "Pochodna U"), input("v", "v", "Wartość V"), input("u", "u", "Wartość U"), input("dv", "v′", "Pochodna V")], output: output("(uv)'", "Pochodna iloczynu"), expression: "du * v + u * dv", tags: ["pochodna", "reguła"] },

  { id: "mean-three", name: "Średnia — 3 wartości", category: "Statystyka", equation: "x̄ = (x₁+x₂+x₃)/3", description: "Średnia arytmetyczna trzech obserwacji.", inputs: [input("x1", "x₁", "Obserwacja 1"), input("x2", "x₂", "Obserwacja 2"), input("x3", "x₃", "Obserwacja 3")], output: output("x̄", "Średnia"), expression: "(x1 + x2 + x3) / 3", tags: ["średnia"] },
  { id: "variance-three", name: "Wariancja populacji — 3 wartości", category: "Statystyka", equation: "σ² = Σ(xᵢ−μ)²/3", description: "Wariancja trzech obserwacji traktowanych jako cała populacja.", inputs: [input("x1", "x₁", "Obserwacja 1"), input("x2", "x₂", "Obserwacja 2"), input("x3", "x₃", "Obserwacja 3"), input("mean", "μ", "Średnia")], output: output("σ²", "Wariancja"), expression: "((x1 - mean) ^ 2 + (x2 - mean) ^ 2 + (x3 - mean) ^ 2) / 3", tags: ["wariancja"] },
  { id: "stddev-three", name: "Odchylenie standardowe — 3 wartości", category: "Statystyka", equation: "σ = √[Σ(xᵢ−μ)²/3]", description: "Odchylenie standardowe populacji trzech obserwacji.", inputs: [input("x1", "x₁", "Obserwacja 1"), input("x2", "x₂", "Obserwacja 2"), input("x3", "x₃", "Obserwacja 3"), input("mean", "μ", "Średnia")], output: output("σ", "Odchylenie"), expression: "sqrt(((x1 - mean) ^ 2 + (x2 - mean) ^ 2 + (x3 - mean) ^ 2) / 3)", tags: ["odchylenie"] },
  { id: "correlation-from-covariance", name: "Korelacja z kowariancji", category: "Statystyka", equation: "r = cov(X,Y)/(σₓσᵧ)", description: "Współczynnik korelacji liniowej z kowariancji i odchyleń.", inputs: [input("covariance", "cov", "Kowariancja"), input("stdX", "σₓ", "Odchylenie X"), input("stdY", "σᵧ", "Odchylenie Y")], output: output("r", "Korelacja"), expression: "covariance / (stdX * stdY)", tags: ["korelacja"] },
  { id: "variation-coefficient", name: "Współczynnik zmienności", category: "Statystyka", equation: "CV = σ/μ·100%", description: "Względne zróżnicowanie danych względem średniej.", inputs: [input("stddev", "σ", "Odchylenie"), input("mean", "μ", "Średnia")], output: output("CV", "Zmienność", "%"), expression: "stddev / mean * 100", tags: ["zmienność"] },

  { id: "conditional-probability", name: "Prawdopodobieństwo warunkowe", category: "Prawdopodobieństwo", equation: "P(A|B)=P(A∩B)/P(B)", description: "Szansa zdarzenia A przy założeniu, że B zaszło.", inputs: [input("pBoth", "P(A∩B)", "Część wspólna"), input("pB", "P(B)", "Prawdopodobieństwo B")], output: output("P(A|B)", "Prawdopodobieństwo"), expression: "pBoth / pB", tags: ["warunkowe"] },
  { id: "bayes-theorem", name: "Twierdzenie Bayesa", category: "Prawdopodobieństwo", equation: "P(A|B)=P(B|A)P(A)/P(B)", description: "Aktualizacja prawdopodobieństwa hipotezy po obserwacji.", inputs: [input("pBgivenA", "P(B|A)", "Wiarygodność"), input("pA", "P(A)", "Prawdopodobieństwo A"), input("pB", "P(B)", "Prawdopodobieństwo B")], output: output("P(A|B)", "Posterior"), expression: "pBgivenA * pA / pB", tags: ["Bayes"] },

  { id: "cagr", name: "Średnioroczna stopa wzrostu", category: "Finanse", equation: "CAGR=(K₁/K₀)^(1/n)−1", description: "Stała roczna stopa prowadząca od wartości początkowej do końcowej.", inputs: [input("initial", "K₀", "Wartość początkowa"), input("final", "K₁", "Wartość końcowa"), input("years", "n", "Liczba lat")], output: output("CAGR", "Stopa wzrostu"), expression: "(final / initial) ^ (1 / years) - 1", tags: ["wzrost", "inwestycje"] },
  { id: "present-value", name: "Wartość bieżąca", category: "Finanse", equation: "PV = FV/(1+r)ⁿ", description: "Dzisiejsza wartość przyszłej kwoty.", inputs: [input("future", "FV", "Wartość przyszła"), input("rate", "r", "Stopa na okres"), input("periods", "n", "Liczba okresów")], output: output("PV", "Wartość bieżąca"), expression: "future / (1 + rate) ^ periods", tags: ["dyskontowanie"] },
  { id: "loan-payment", name: "Rata annuitetowa", category: "Finanse", equation: "A = Kr(1+r)ⁿ/[(1+r)ⁿ−1]", description: "Stała rata kredytu przy stopie r na okres.", inputs: [input("principal", "K", "Kapitał"), input("rate", "r", "Stopa na okres"), input("periods", "n", "Liczba rat")], output: output("A", "Rata"), expression: "principal * rate * (1 + rate) ^ periods / ((1 + rate) ^ periods - 1)", tags: ["kredyt", "rata"] },

  { id: "constant-stefan", name: "Stała: Stefana–Boltzmanna", category: "Stałe", equation: "σ = 5,670374419·10⁻⁸ W/(m²K⁴)", description: "Stała prawa promieniowania ciała doskonale czarnego.", inputs: [], output: output("σ", "Stała Stefana", "W/(m²K⁴)"), expression: "5.670374419e-8", tags: ["stała", "promieniowanie"] },
  { id: "escape-velocity", name: "Prędkość ucieczki", category: "Fizyka: grawitacja", equation: "vₑ = √(2GM/r)", description: "Minimalna prędkość opuszczenia pola masy M bez dalszego napędu.", inputs: [input("G", "G", "Stała grawitacyjna"), input("mass", "M", "Masa centralna", "kg"), input("radius", "r", "Odległość od środka", "m")], output: output("vₑ", "Prędkość ucieczki", "m/s"), expression: "sqrt(2 * G * mass / radius)", tags: ["grawitacja", "orbita"] },
  { id: "torque", name: "Moment siły", category: "Fizyka: siły", equation: "τ = rFsinα", description: "Zdolność siły do wywołania obrotu wokół osi.", inputs: [input("radius", "r", "Ramię", "m"), input("force", "F", "Siła", "N"), input("angle", "α", "Kąt", "rad")], output: output("τ", "Moment siły", "N·m"), expression: "radius * force * sin(angle)", tags: ["obrót"] },
  { id: "point-inertia", name: "Moment bezwładności punktu", category: "Fizyka: energia", equation: "I = mr²", description: "Moment bezwładności masy punktowej względem osi.", inputs: [input("mass", "m", "Masa", "kg"), input("radius", "r", "Odległość od osi", "m")], output: output("I", "Moment bezwładności", "kg·m²"), expression: "mass * radius ^ 2", tags: ["obrót"] },
  { id: "rotational-energy", name: "Energia ruchu obrotowego", category: "Fizyka: energia", equation: "E = Iω²/2", description: "Energia kinetyczna obracającego się ciała.", inputs: [input("inertia", "I", "Moment bezwładności", "kg·m²"), input("angularVelocity", "ω", "Prędkość kątowa", "rad/s")], output: output("E", "Energia", "J"), expression: "inertia * angularVelocity ^ 2 / 2", tags: ["obrót"] },
  { id: "angular-momentum", name: "Moment pędu", category: "Fizyka: energia", equation: "L = Iω", description: "Odpowiednik pędu dla ruchu obrotowego.", inputs: [input("inertia", "I", "Moment bezwładności", "kg·m²"), input("angularVelocity", "ω", "Prędkość kątowa", "rad/s")], output: output("L", "Moment pędu", "kg·m²/s"), expression: "inertia * angularVelocity", tags: ["obrót"] },
  { id: "stefan-boltzmann", name: "Prawo Stefana–Boltzmanna", category: "Fizyka: ciepło", equation: "P = σεAT⁴", description: "Moc promieniowania cieplnego powierzchni o emisyjności ε.", inputs: [input("sigma", "σ", "Stała Stefana"), input("emissivity", "ε", "Emisyjność"), input("area", "A", "Pole", "m²"), input("temperature", "T", "Temperatura", "K")], output: output("P", "Moc promieniowania", "W"), expression: "sigma * emissivity * area * temperature ^ 4", tags: ["promieniowanie", "temperatura"] },
  { id: "lorentz-factor", name: "Czynnik Lorentza", category: "Fizyka: atom", equation: "γ = 1/√(1−v²/c²)", description: "Współczynnik efektów szczególnej teorii względności.", inputs: [input("velocity", "v", "Prędkość", "m/s"), input("lightSpeed", "c", "Prędkość światła", "m/s")], output: output("γ", "Czynnik Lorentza"), expression: "1 / sqrt(1 - velocity ^ 2 / lightSpeed ^ 2)", tags: ["względność"], assumptions: ["|v| < c"] }
];
